"""
pdf_report.py
-------------
FPDF-based export of an AuditReport into a management-ready PDF:

    1. Cover page with scorecard
    2. Executive summary + risk profile
    3. Theme-by-theme compliance breakdown
    4. Full Annex A control register (93 rows)
    5. Prioritised remediation roadmap with technical fix steps
    6. Appendix: telemetry evidence sample

Uses fpdf2 (`pip install fpdf2`). Core PDF fonts only, so it renders
identically on any machine with no font bundling required.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict

from fpdf import FPDF

NAVY = (17, 34, 64)
SLATE = (71, 85, 105)
LIGHT = (241, 245, 249)
BORDER = (203, 213, 225)
GREEN = (22, 128, 61)
AMBER = (202, 138, 4)
RED = (185, 28, 28)
GREY = (120, 130, 145)
BLUE = (37, 99, 175)

STATUS_COLOR = {
    "PASS": GREEN, "PARTIAL": AMBER, "FAIL": RED,
    "MANUAL": BLUE, "NO_DATA": GREY, "N/A": GREY,
}
RISK_COLOR = {"High": RED, "Medium": AMBER, "Low": GREEN, "None": GREY}


def _ascii(text: Any) -> str:
    """Core PDF fonts are Latin-1 only — normalise anything outside it."""
    s = str(text if text is not None else "")
    repl = {"—": "-", "–": "-", "‘": "'", "’": "'",
            "“": '"', "”": '"', "…": "...", "≥": ">=",
            "≤": "<=", "→": "->", "·": "-", "•": "-"}
    for k, v in repl.items():
        s = s.replace(k, v)
    return s.encode("latin-1", "replace").decode("latin-1")


class AuditPDF(FPDF):
    def __init__(self, org: str, host: str, auditor: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.org = _ascii(org)
        self.host = _ascii(host)
        self.auditor = _ascii(auditor)
        self.set_auto_page_break(auto=True, margin=18)
        self.set_title("ISO 27001 Annex A Compliance Audit Report")
        self.set_author(self.auditor)
        self.cover = True

    # -- chrome ------------------------------------------------------------
    def header(self):
        if self.cover:
            return
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*NAVY)
        self.cell(0, 6, "ISO/IEC 27001:2022 - Annex A Compliance Audit", align="L")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*SLATE)
        self.cell(0, 6, f"{self.org}  |  {self.host}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*BORDER)
        self.line(10, self.get_y() + 1, 200, self.get_y() + 1)
        self.ln(4)

    def footer(self):
        if self.cover:
            return
        self.set_y(-14)
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(*GREY)
        self.cell(0, 5, "Generated by ISO 27001 Compliance Auditor - "
                        "confidential, for internal management use", align="L")
        self.cell(0, 5, f"Page {self.page_no()}", align="R")

    # -- building blocks ---------------------------------------------------
    def h1(self, text):
        self.ln(2)
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(*NAVY)
        self.cell(0, 9, _ascii(text), new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*NAVY)
        self.set_line_width(0.6)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_line_width(0.2)
        self.ln(4)

    def h2(self, text):
        self.ln(2)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*NAVY)
        self.cell(0, 7, _ascii(text), new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def body(self, text, size=9.5, color=SLATE):
        self.set_font("Helvetica", "", size)
        self.set_text_color(*color)
        self.multi_cell(0, 4.8, _ascii(text))
        self.ln(1.5)

    def kv_table(self, pairs, kw=55):
        self.set_font("Helvetica", "", 9)
        for k, v in pairs:
            self.set_fill_color(*LIGHT)
            self.set_text_color(*NAVY)
            self.set_font("Helvetica", "B", 9)
            self.cell(kw, 7, f"  {_ascii(k)}", border=1, fill=True)
            self.set_font("Helvetica", "", 9)
            self.set_text_color(*SLATE)
            self.cell(0, 7, f"  {_ascii(v)}", border=1, new_x="LMARGIN", new_y="NEXT")

    def stat_row(self, items):
        """items = [(label, value, rgb), ...] rendered as coloured stat cards."""
        w = 190 / len(items)
        y = self.get_y()
        for label, value, rgb in items:
            x = 10 + w * items.index((label, value, rgb))
            self.set_xy(x, y)
            self.set_fill_color(*rgb)
            self.set_text_color(255, 255, 255)
            self.set_font("Helvetica", "B", 17)
            self.cell(w - 2, 12, _ascii(value), border=0, fill=True, align="C",
                      new_x="LEFT", new_y="NEXT")
            self.set_x(x)
            self.set_fill_color(*LIGHT)
            self.set_text_color(*NAVY)
            self.set_font("Helvetica", "B", 7.5)
            self.cell(w - 2, 6, _ascii(label).upper(), border=0, fill=True, align="C")
        self.set_xy(10, y + 20)

    def bar(self, pct, width=190, height=7, color=BLUE):
        x, y = self.get_x(), self.get_y()
        self.set_fill_color(*LIGHT)
        self.rect(x, y, width, height, style="F")
        self.set_fill_color(*color)
        self.rect(x, y, max(0.5, width * min(max(pct, 0), 100) / 100.0), height, style="F")
        self.set_draw_color(*BORDER)
        self.rect(x, y, width, height)
        self.set_xy(x, y + height + 2)

    def table(self, headers, widths, rows, color_col=None, color_map=None,
              font_size=7.6, row_h=5.4):
        self.set_font("Helvetica", "B", font_size)
        self.set_fill_color(*NAVY)
        self.set_text_color(255, 255, 255)
        for h, w in zip(headers, widths):
            self.cell(w, 6.4, f" {_ascii(h)}", border=0, fill=True, align="L")
        self.ln()
        self.set_font("Helvetica", "", font_size)
        stripe = False
        for row in rows:
            if self.get_y() > 268:
                self.add_page()
                self.set_font("Helvetica", "B", font_size)
                self.set_fill_color(*NAVY)
                self.set_text_color(255, 255, 255)
                for h, w in zip(headers, widths):
                    self.cell(w, 6.4, f" {_ascii(h)}", border=0, fill=True)
                self.ln()
                self.set_font("Helvetica", "", font_size)
            self.set_fill_color(*(LIGHT if stripe else (255, 255, 255)))
            stripe = not stripe
            for i, (cell, w) in enumerate(zip(row, widths)):
                txt = _ascii(cell)
                if color_col is not None and i == color_col and color_map:
                    self.set_text_color(*color_map.get(str(cell), SLATE))
                    self.set_font("Helvetica", "B", font_size)
                else:
                    self.set_text_color(*SLATE)
                    self.set_font("Helvetica", "", font_size)
                # truncate to fit
                while self.get_string_width(txt) > w - 2.5 and len(txt) > 4:
                    txt = txt[:-2]
                    if self.get_string_width(txt + "..") <= w - 2.5:
                        txt += ".."
                        break
                self.cell(w, row_h, f" {txt}", border=0, fill=True)
            self.ln()
        self.set_text_color(*SLATE)


# ---------------------------------------------------------------------------
# Report builder
# ---------------------------------------------------------------------------

def build_pdf(report, org="Organisation", auditor="Information Security",
              scope_note="", include_register=True, include_roadmap=True,
              include_appendix=True) -> bytes:
    d: Dict[str, Any] = report.to_dict()
    pdf = AuditPDF(org, d["host"], auditor)

    # ---------------- Cover ----------------
    pdf.add_page()
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, 210, 78, style="F")
    pdf.set_xy(14, 20)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 26)
    pdf.cell(0, 12, "ISO/IEC 27001:2022", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(14)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "Annex A Compliance Audit Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(14)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 9, _ascii(org), new_x="LMARGIN", new_y="NEXT")

    pdf.set_xy(10, 92)
    score = d["compliance_score"]
    band = GREEN if score >= 75 else (AMBER if score >= 50 else RED)
    pdf.stat_row([
        ("Weighted compliance", f"{score}%", band),
        ("Controls passed", str(d["counts"]["PASS"]), GREEN),
        ("Controls failed", str(d["counts"]["FAIL"] + d["counts"]["PARTIAL"]), RED),
        ("High risks open", str(d["risk_counts"]["High"]), RED),
    ])

    pdf.ln(2)
    pdf.set_x(10)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 6, "Weighted compliance against assessed Annex A controls",
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(10)
    pdf.bar(score, color=band, height=9)
    pdf.ln(4)

    pdf.kv_table([
        ("Report date", datetime.now().strftime("%d %B %Y")),
        ("Assessment timestamp", d["generated_utc"]),
        ("Target system", d["host"]),
        ("Operating system", d["os"]),
        ("Framework", "ISO/IEC 27001:2022 Annex A (93 controls)"),
        ("Assessment coverage", f"{d['coverage']}% of Annex A controls"),
        ("Maturity rating", d["maturity"]),
        ("Prepared by", auditor),
        ("Classification", "CONFIDENTIAL - Internal use only"),
    ], kw=55)

    if scope_note:
        pdf.ln(3)
        pdf.h2("Scope and limitations")
        pdf.body(scope_note)

    pdf.cover = False

    # ---------------- Executive summary ----------------
    pdf.add_page()
    pdf.h1("1. Executive Summary")

    c = d["counts"]
    total = sum(c.values())
    assessed = c["PASS"] + c["PARTIAL"] + c["FAIL"]
    pdf.body(
        f"This report presents the results of an automated gap analysis of {d['host']} against "
        f"all {total} controls of ISO/IEC 27001:2022 Annex A. Configuration telemetry was "
        f"collected from the target system and evaluated against a defined security baseline.\n\n"
        f"Of the {total} Annex A controls, {assessed} were assessed using technical evidence. "
        f"{c['PASS']} are fully implemented, {c['PARTIAL']} are partially implemented and "
        f"{c['FAIL']} are not implemented. A further {c['MANUAL']} controls are organisational "
        f"or procedural in nature and require documented auditor attestation, and {c['NO_DATA']} "
        f"could not be evaluated because the required telemetry was not present in the "
        f"submitted dataset.\n\n"
        f"The resulting weighted compliance score is {score}% "
        f"(unweighted pass rate {d['raw_score']}%), placing the system in the "
        f"'{d['maturity']}' band. Scoring weights each control by the severity of its "
        f"associated risk (High 5, Medium 3, Low 1) so that a failure of a critical control "
        f"depresses the score more than a failure of a minor one.\n\n"
        f"Assessment coverage was {d['coverage']}% — that is, {assessed} of the {total} "
        f"Annex A controls produced a definitive verdict from the evidence available.")

    if d.get("coverage_warning"):
        pdf.ln(1)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*RED)
        pdf.set_fill_color(254, 226, 226)
        pdf.multi_cell(0, 5, _ascii(f"  COVERAGE CAVEAT: {d['coverage_warning']}"),
                       border=1, fill=True)
        pdf.ln(3)
        pdf.set_text_color(*SLATE)

    pdf.h2("Open risk profile")
    rc = d["risk_counts"]
    pdf.body(
        f"{rc['High']} high, {rc['Medium']} medium and {rc['Low']} low risk findings are "
        f"currently open. High risk findings represent controls whose failure could directly "
        f"lead to loss of confidentiality, integrity or availability of information assets and "
        f"should be treated as the immediate remediation priority.")
    for level in ("High", "Medium", "Low"):
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*RISK_COLOR[level])
        pdf.cell(26, 7, f" {level} risk")
        pdf.set_text_color(*SLATE)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(14, 7, str(rc[level]))
        y = pdf.get_y()
        pdf.set_xy(52, y + 1)
        pdf.bar(100.0 * rc[level] / max(1, sum(rc.values())), width=145, height=5,
                color=RISK_COLOR[level])
        pdf.set_xy(10, y + 7)
    pdf.ln(3)

    pdf.h2("Status distribution")
    pdf.table(
        ["Status", "Controls", "Meaning"],
        [30, 22, 138],
        [["PASS", c["PASS"], "All configured technical checks satisfied"],
         ["PARTIAL", c["PARTIAL"], "Some checks satisfied - control partially effective"],
         ["FAIL", c["FAIL"], "No checks satisfied - control not effective"],
         ["MANUAL", c["MANUAL"], "Procedural control awaiting documented attestation"],
         ["NO_DATA", c["NO_DATA"], "Required telemetry absent from the submitted dataset"],
         ["N/A", c["N/A"], "Explicitly scoped out of this assessment"]],
        color_col=0, color_map=STATUS_COLOR, font_size=8.5, row_h=6)

    # ---------------- Theme breakdown ----------------
    pdf.add_page()
    pdf.h1("2. Compliance by Annex A Theme")
    pdf.body(
        "Annex A of ISO/IEC 27001:2022 organises its 93 controls into four themes. The table "
        "below shows how the target system performs within each.")

    theme_rows = []
    for t in d["themes"]:
        theme_rows.append([t["Theme"], t["Total"], t["PASS"], t["PARTIAL"], t["FAIL"],
                           t["MANUAL"], t["NO_DATA"], f"{t['Compliance %']}%"])
    pdf.table(["Theme", "Total", "Pass", "Partial", "Fail", "Manual", "No data", "Compliance"],
              [46, 18, 18, 20, 18, 22, 22, 26], theme_rows, font_size=8.5, row_h=6.4)
    pdf.ln(4)

    for t in d["themes"]:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*NAVY)
        pdf.cell(50, 6, _ascii(t["Theme"]))
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*SLATE)
        pdf.cell(16, 6, f"{t['Compliance %']}%")
        y = pdf.get_y()
        pdf.set_xy(76, y + 0.8)
        pct = t["Compliance %"]
        pdf.bar(pct, width=122, height=4.5,
                color=GREEN if pct >= 75 else (AMBER if pct >= 50 else RED))
        pdf.set_xy(10, y + 6.5)
    pdf.ln(4)

    pdf.h2("Highest impact open findings")
    high = [r for r in d["controls"]
            if r["risk"] == "High" and r["status"] in ("FAIL", "PARTIAL")][:12]
    if high:
        pdf.table(["Control", "Title", "Status", "Finding"],
                  [20, 52, 20, 98],
                  [[r["id"], r["title"], r["status"], r["evidence"]] for r in high],
                  color_col=2, color_map=STATUS_COLOR)
    else:
        pdf.body("No high risk findings are currently open.")

    # ---------------- Control register ----------------
    if include_register:
        pdf.add_page()
        pdf.h1("3. Annex A Control Register")
        pdf.body(
            "Complete assessment result for every ISO/IEC 27001:2022 Annex A control. "
            "'Mode' indicates whether the control was evaluated automatically from telemetry, "
            "by auditor attestation, or a combination of both.")
        rows = [[r["id"], r["title"], r["theme"][:14], r["mode"].capitalize(),
                 r["status"], r["risk"],
                 f"{sum(1 for ch in r['checks'] if ch['passed'])}/{len(r['checks'])}"
                 if r["checks"] else "-"]
                for r in d["controls"]]
        pdf.table(["Control", "Title", "Theme", "Mode", "Status", "Risk", "Checks"],
                  [20, 74, 26, 22, 22, 16, 16], rows,
                  color_col=4, color_map=STATUS_COLOR, font_size=7.4, row_h=5.0)

    # ---------------- Roadmap ----------------
    if include_roadmap:
        pdf.add_page()
        pdf.h1("4. Remediation Roadmap")
        pdf.body(
            "Findings are prioritised by risk level and grouped into delivery phases. "
            "Each entry lists the specific checks that failed and the technical steps required "
            "to close the gap. Phase 1 items should be scheduled immediately.")

        roadmap = d["roadmap"]
        summary_rows = [[r["Priority"], r["Control"], r["Title"], r["Risk"],
                         r["Status"], r["Target Window"]] for r in roadmap[:40]]
        pdf.table(["#", "Control", "Title", "Risk", "Status", "Target"],
                  [10, 20, 84, 20, 24, 28], summary_rows,
                  color_col=3, color_map=RISK_COLOR, font_size=7.6, row_h=5.2)

        detail = [r for r in roadmap if r["Status"] in ("FAIL", "PARTIAL")][:25]
        if detail:
            pdf.add_page()
            pdf.h1("5. Technical Remediation Detail")
            for item in detail:
                if pdf.get_y() > 232:
                    pdf.add_page()
                pdf.set_fill_color(*LIGHT)
                pdf.set_draw_color(*BORDER)
                pdf.set_font("Helvetica", "B", 9.5)
                pdf.set_text_color(*NAVY)
                pdf.cell(150, 7, f"  {item['Control']} - {_ascii(item['Title'])}",
                         border="LTB", fill=True)
                pdf.set_text_color(*RISK_COLOR.get(item["Risk"], SLATE))
                pdf.set_font("Helvetica", "B", 8.5)
                pdf.cell(40, 7, f"{item['Risk']} risk  |  {item['Status']}  ",
                         border="RTB", fill=True, align="R", new_x="LMARGIN", new_y="NEXT")

                if item["Failed Checks"]:
                    pdf.set_font("Helvetica", "I", 8)
                    pdf.set_text_color(*RED)
                    pdf.multi_cell(0, 4.2, _ascii("Failed: " + "; ".join(item["Failed Checks"])))
                pdf.set_font("Helvetica", "", 8.6)
                pdf.set_text_color(*SLATE)
                for step in item["Remediation Steps"]:
                    pdf.set_x(13)
                    pdf.multi_cell(0, 4.4, _ascii("-  " + step))
                pdf.ln(3)

    # ---------------- Appendix ----------------
    if include_appendix:
        pdf.add_page()
        pdf.h1("Appendix A - Telemetry Evidence")
        pdf.body(
            "Extract of the configuration parameters ingested for this assessment. "
            "These values constitute the technical evidence underpinning the automated results.")
        flat = report.flat
        keys = sorted(k for k in flat if not k.startswith("attestations."))
        rows = []
        for k in keys[:150]:
            v = flat[k]
            if isinstance(v, list):
                v = ", ".join(str(x) for x in v[:5]) or "(none)"
            elif isinstance(v, bool):
                v = "True" if v else "False"
            elif v is None:
                v = "(not collected)"
            rows.append([k, str(v)])
        pdf.table(["Parameter", "Observed value"], [104, 86], rows,
                  font_size=7.2, row_h=4.8)
        if len(keys) > 150:
            pdf.ln(2)
            pdf.body(f"({len(keys) - 150} further parameters omitted for brevity.)", size=8)

    out = pdf.output()
    return bytes(out)
